CREATE DATABASE DB_VENDAS;

CREATE TABLE TB_LOJA (id_loja INT PRIMARY KEY NOT NULL, cidade VARCHAR(70), estado VARCHAR(60));

CREATE TABLE TB_PRODUTO (id_produto INT PRIMARY KEY NOT NULL, nome_produto VARCHAR(100), categoria VARCHAR(60), segmento VARCHAR(50), marca VARCHAR(50));

CREATE TABLE TB_VENDEDOR (id_vendedor INT PRIMARY KEY NOT NULL, nome_vendedor VARCHAR(50), sobrenome VARCHAR(50));

CREATE TABLE TB_DATA (data_completa DATE PRIMARY KEY NOT NULL, DIA INT, MES INT, ANO INT);

CREATE TABLE TB_VENDAS (id_venda INT PRIMARY KEY NOT NULL, id_produto INT PRIMARY KEY NOT NULL, id_loja INT PRIMARY KEY NOT NULL, id_vendedor INT PRIMARY KEY NOT NULL, data_completa DATE PRIMARY KEY NOT NULL, valor_venda NUMERIC(10,2));

--CONSTRAINTS
ALTER TABLE TB_VENDAS ADD CONSTRAINT fk_vendedor FOREIGN KEY (id_vendedor) REFERENCES TB_VENDEDOR (id_vendedor);

ALTER TABLE TB_VENDAS ADD CONSTRAINT fk_produto FOREIGN KEY (id_produto) REFERENCES TB_PRODUTO (id_produto);

ALTER TABLE TB_VENDAS ADD CONSTRAINT fk_loja FOREIGN KEY (id_loja) REFERENCES TB_LOJA (id_loja);

